---
title: "Skript-Vorlage"
mainfont: "Palatino Linotype"
sansfont: "Arial"
monofont: "Consolas"
mathfont: "STIX Two Text"
---

```{r setup, include=FALSE}
# ---------------------------------------------------------------------------
# Einige Funktionen und Variabeln sind in die Datei 'prelude.R' ausgelagert.
# Diese werden hier nachgeladen und angepasst.
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
source("prelude.R")
initPrelude(
    "VOR-",        # Prefix für Terminlisten etc.
    TRUE           # Soll geprüft werden ob alle Pakete installiert sind?
)

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# Sichert zu, dass die entsprechenden Daten auch vorhanden sind. 
# Ggf. werden sie von dem übergebenden Link geladen und lokal gespeichert.
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# tips <- assertData("tips.csv", "https://goo.gl/whKjnl")

# ---------------------------------------------------------------------------
```
```{r localKnitrButtonSetup, eval=!RENDEREDBYSCRIPT, echo=FALSE, include=FALSE}
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# Einstellungen für den Fall, dass man den knitr-Button nutzt. Sonst bitte
# 'eval=FALSE' einstellen!
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

privateVorstellung <<- FALSE   # Zeige die Private Vorstellung
showVorlesungsplan <<- FALSE  # Zeige den Vorlesungsplan
UseCache <<- FALSE


if (!exists("prelude.rendertools")) {
    loadPrelude("prelude_rendertools.R")
}

createPrivateYaml("Dozent*in", "SoSe 2020", "Studienort")

# Erzeuge Skript "DozentenSkript", "StudierendenSkript" oder "LösungsSkript": 
makeSkriptOfType("DozentenSkript") 
```

```{r setUpChildren, eval=TRUE, include=FALSE}
childrenToInclude <- c(
    "Kind-Vorlage"
)
if (FALSE) { # Zum debuggen auf TRUE setzen!
  childrenToInclude <- c("Kind-Vorlage")
}
includeChild <- function(name, children=childrenToInclude, all=FALSE) {
    ifelse(all, TRUE, ifelse(name %in% children, TRUE, FALSE))
}
```



```{r child = './Inhalte/Kind-Vorlage.Rmd', eval=includeChild("Kind-Vorlage")}
```

```{r child = './private/private-Vorstellung.Rmd', eval = privateVorstellung}
```


```{r finalize, include=FALSE}
# ---------------------------------------------------------------------------
# Setzt einige Parameter zurück.
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
finalizePrelude()
```
